### ISSUE TITLE
ThemeMaster updates loop

### ISSUE THREAD

**Issue by christianhaitian** [JohnIrvine1433/ThemeMaster#14]
Hi John,

Per the report here, https://github.com/christianhaitian/arkos/issues/760, thememaster is looping after an update in ArkOS.  The solution per that ticket I linked to is to manually load the latest zip and install it that way.  Let me know if there's anything I can do to help resolve this issue or anything else that may help future thememaster updates to be easier to manage with ArkOS.

Thanks,

**Comment by JohnIrvine1433** [comment]
Thanks for the info, I had published the previous release before pushing all the updates...
It's fixed now.
