### ISSUE TITLE
Extra feature - Remove Data folder

### ISSUE THREAD

**Issue by Andoramb** [JohnIrvine1433/ThemeMaster#23]
Hey 🙂 

I think in case of a failed download (like ssl fail), it would be useful to have a `function DeleteData()` in `Settings`, that does an `rm  -rf ./data/`, so upon next launch it could try to redownload again?

What do you think?

**Comment by JohnIrvine1433** [comment]
Definitely, I'll do it

**Comment by JohnIrvine1433** [comment]
Implemented in latest release 4.8.0
