### ISSUE TITLE
Theme Master Update infinite loop

### ISSUE THREAD

**Issue by lauren7ino** [JohnIrvine1433/ThemeMaster#24]
Hi
I've got into a Theme Master Update infinite loop that I can not get rid off.

But I noticed this message.
ThemeMaster: line 424: [: missing `]'

https://github.com/JohnIrvine1433/ThemeMaster/assets/9194198/8b7a18d2-cc1e-440e-9ebe-caae03b65b32

I hope you can fix this.

RG353M, ARKOS latest.

Thanks

**Comment by JohnIrvine1433** [comment]
Thanks, fixed in latest release 4.8.0

**Comment by lauren7ino** [comment]
Confirmed the fix. Thanks
