### ISSUE TITLE
Names Platforms 

### ISSUE THREAD

**Issue by aksenav2** [JohnIrvine1433/ThemeMaster#26]
Hello, please tell me where are located in the arkos system, the names of the platforms/emulators. I didn't find them in the themes resources. 
![IMG_20240411_222228](https://github.com/JohnIrvine1433/ThemeMaster/assets/110097689/80a4c255-34cc-4411-bcc7-ccd48553c2f8)

**Comment by JohnIrvine1433** [comment]
Hi, I think what you're referring to is part of ES theme, text can be defined in theme.xml file or part of the image.

**Comment by aksenav2** [comment]
> Hi, I think what you're referring to is part of ES theme, text can be defined in theme.xml file or part of the image.

There are no such texts in the resources of the themes.

**Comment by JohnIrvine1433** [comment]
What theme are you using ? It might be part of the picture...

**Comment by aksenav2** [comment]
> What theme are you using ? It might be part of the picture...
ES-THEME-ALBEDO No, it's not part of the graphics, I've redrawn almost all of the graphics to my own.

**Comment by JohnIrvine1433** [comment]
Don't know about it, best would probably to ask mluizvitor

**Comment by aksenav2** [comment]
> Don't know about it, best would probably to ask mluizvitor

Thank you
