### ISSUE TITLE
Thememaster crashes upon selecting "Uninstall a theme" (Anbernic RG353VS)

### ISSUE THREAD

**Issue by Giuleus957** [JohnIrvine1433/ThemeMaster#27]
I'm running latest ArkOS (04/24/2024) and latest Thememaster (4.8.1) on my Anbernic RG353VS and when I select "Uninstall a theme" Thememaster crashes. All the rest of Thememaster works fine, I can install new themes etc. but crashes only when I select "Uninstall a theme".

**Comment by manasv** [comment]
Same for me I think is something related to the latest update (4.8.1) as I reverted to (4.8.0) and it stopped crashing but still I have some issues because is not able to fetch data from the repositories because of SSL failure.

**Comment by JohnIrvine1433** [comment]
Hi everyone, sorry for the late reply I was away for a while. I'll fix it in the coming day.

**Comment by JohnIrvine1433** [comment]
I have pushed v4.9.0 as prerelease, should do the job.

**Comment by manasv** [comment]
Can confirm that 4.9.0 fixed the problem on my side, thank you.
