### ISSUE TITLE
Not showing in port master

### ISSUE THREAD

**Issue by Unknowns0n** [JohnIrvine1433/ThemeMaster#28]
New attempted installation of Theme Master on Jelos Powkiddy RGB30, is not showing up in port master to attempt installing. 
Followed installation instructions and  nothing, port master still functional regardless.

**Comment by JohnIrvine1433** [comment]
Hi, it is probably a problem within the gamelist.xml file that has not been updated. Try to restart emulationstation to force a refresh. 
NB : following JELOS end of life I'll be dropping support to this OS since I'm using the comm command that is not available on JELOS.

**Comment by Unknowns0n** [comment]
I have since installed Arkos and theme master worked just fine, thank you for your response.
