### ISSUE TITLE
SSL Verification Failure

### ISSUE THREAD

**Issue by TrashGarbage** [JohnIrvine1433/ThemeMaster#3]
ArkOS 1.7 (06042021)
Installed to sd2/tools

Full Error Reads:

SSL verification failure. 
ERROR: cannot verfiy
raw.githubusercontent.com's certificate, issues by 'CN=DigiCert SHA2 High Assurance Server CA, OU=www.digicert.com, 
O=DigiCert Inc, C=US' : Issued certificate not yet valid.  
To connect to raw.githubusercontent.com insecurely, use '--no-check-certificate'.

**Comment by JohnIrvine1433** [comment]
Connection to raw.githubusercontent.com is now set insecurely ('--no-check-certificate' option) from version 3.1.1
