### ISSUE TITLE
RGB30 Not working with Rocknix

### ISSUE THREAD

**Issue by aenertia** [JohnIrvine1433/ThemeMaster#31]
Using latest HEAD and/or the release.

Launching results in a 'unable to find control' dialog. Adding the correct /dev/<event> path for the Mainline joypad and setting to x55/anbernic results in non-usable controls but the app launching into menu.

Rocknix has Sway/wl compositor - so should thememaster simply inherit/check and inherit the wayland input controls?

**Comment by JohnIrvine1433** [comment]
Could you confirm the /dev/input/ you're having for pad's control and run evtest against it?

**Comment by josemalop** [comment]
Same issue on Anbernic RG353P.

**Comment by JohnIrvine1433** [comment]
@josemalop can you try and report with the enclosed file ?
[ThemeMaster.zip](https://github.com/user-attachments/files/16041403/ThemeMaster.zip)

**Comment by JohnIrvine1433** [comment]
@josemalop could you try putting the enclosed file in ThemeMaster's folder and report if it's working ?
[paramcontrols.txt](https://github.com/user-attachments/files/16041506/paramcontrols.txt)

**Comment by JohnIrvine1433** [comment]
I have published v4.11.1 as pre-release, from everything I gather it should fix the issue but I cannot confirm as I do not have a device with an rk3588 chip ... Could one of you test it ? @aenertia @josemalop

**Comment by josemalop** [comment]
Works like a charm!! Thank you very much for your effort! :-)
