### ISSUE TITLE
Installing themes on thememaster for r36s not working!

### ISSUE THREAD

**Issue by retrotetro** [JohnIrvine1433/ThemeMaster#34]
Every time i try and install a theme it comes up with ' theme's installation have failed because the archive did not download correctly. check your connection and try again.' My connection is fine though.

**Comment by JohnIrvine1433** [comment]
Could you run it again in debug mode and give me the content of the debug file that would have been created?

**Comment by retrotetro** [comment]
whats debug mode, is on retroarch?

**Comment by JohnIrvine1433** [comment]
Within ThemeMaster menu : Settings > Advanced settings
Once you reproduce the bug you can exit ThemeMaster and get the debug folder that would have been created inside ThemeMaster's folder.
