### ISSUE TITLE
How do i copy a theme folder from one r36s to another???

### ISSUE THREAD

**Issue by retrotetro** [JohnIrvine1433/ThemeMaster#35]
So my friends r36s theme folder is empty and i was wondering if it would be possible to copy a theme from my r36s to his? If it is possible then how?

**Comment by JohnIrvine1433** [comment]
Yes you can just copy a theme's folder from one device to another, they are stored in /roms/themes/ or /etc/emulationstation/themes/ or 
 /storage/.config/emulationstation/themes/ (depending on your OS)

**Comment by retrotetro** [comment]
ok thx,
i have ArkOs and have attempted just copying it on but when i started up the console no theme option was available?

**Comment by JohnIrvine1433** [comment]
You need to change it from emulationstation by pressing Start and accessing the associated submenu

**Comment by retrotetro** [comment]
whats the associated submenu?

**Comment by retrotetro** [comment]
do you think flashing OS could just get the theme folder to reappear?

**Comment by JohnIrvine1433** [comment]
Installed themes (from ThemeMaster or manually by copying them in the right folder) can be chosen from ES menu > UI settings > Theme

**Comment by retrotetro** [comment]
but once i'm on ui settings there is no theme option. apparently the stock sd card isnt good and is corrupted

**Comment by JohnIrvine1433** [comment]
Ok, nothing that can be done on my side then...
