### ISSUE TITLE
[enhancement request] Add Update / Install All Options in theme installation and update menus.

### ISSUE THREAD

**Issue by AngelofWoe** [JohnIrvine1433/ThemeMaster#7]
Request to add Update / Install All Themes options in theme installation and update menus.

**Comment by JohnIrvine1433** [comment]
Implemented on the nightly branch.
@AngelofWoe if you want to give it a try and tell me if that's ok.

**Comment by AngelofWoe** [comment]
Seems to work quite well.

An option to skip the confirmation prompts between each theme (the '<themename> has been successfully installed' > OK prompt) wouldn't hurt but this is already much more convenient when installing many themes, thank you. In the case of installations I can also see someone wanting the ability to select multiple specific themes for installing but not necessarily all of them, but I also know that'd require more work.

The ability to update all outdated themes at once is perfect.

**Comment by JohnIrvine1433** [comment]
Ok, I've implemented the additional features on the nightly branch but it needs some testing. I'll probably push it on the master branch this WE. Still time to make few adjustments !

**Comment by AngelofWoe** [comment]
Skipping the prompts between themes and the counter are working excellently.

Install / Update All only installs/updates the selected themes instead of all available themes, so it functions identically to selected at the moment and won't run unless items are selected.

Can we add these features to Uninstall/Reinstall themes as well? I did a lot of uninstalling while testing (although I suppose I could have just deleted the files again).

**Comment by JohnIrvine1433** [comment]
Thanks for your feedback, I'll tqke account of it before releasing the version.

**Comment by AngelofWoe** [comment]
Thank you so much for all your hard work.

**Comment by JohnIrvine1433** [comment]
@AngelofWoe, having gone through it I decided that it might be better to leave a simple list for Uninstall and Reinstall menus. Usually you don't intend to remove or reinstall several themes at once and it's way faster to remove one with a simple list than with a checklist... as you said during tests you can always delete the files.
Otherwise everything should be working smoothly now.

**Comment by JohnIrvine1433** [comment]
Version 4.0.0 now released !
