### ISSUE TITLE
Appear offline since most recent update

### ISSUE THREAD

**Issue by jondeckert** [JohnIrvine1433/ThemeMaster#9]
Hi there, thank you for your work on ThemeMaster.

I updated to the most recent version and now I get a message saying "you appear to be offline, ThemeMaster require an internet access to run!" 

In order to exit this screen on my RGB10, I have to press the reset button since no other button combinations work. I can confirm that my RGB10 is online by successfully accessing PortMaster.

I've attempted to fix the issue by removing and reinstalling ThemeMaster from a fresh download from GitHub but the same issue persists.

**Comment by DragoLord19D** [comment]
It's working for my MP
